// ctrl+alt+E to activate local env in the file
@apiPath=/bikes
@host={{base_url}}{{apiPath}}

@bikeID=62ea8b6b812d11aa73b7ea79
@stationId=62efeb6ebc0d3ca314556246

### Get All Bikes
GET /

### Get Bike Details
GET /{{bikeID}}

### Add New Bike
POST /
    Content-Type: application/json
    Authorization: Bearer {{jwtToken}}


### Get Last Bike Location(s)
GET /location/{{bikeID}}
    ?limit=5

### Update Bike Location
PATCH /location/{{bikeID}}
Authorization: Bearer {{jwtToken}}

{
    "location":{
        "latitude": 100,
        "longitude": 100
    }
}

### Rent Bike
POST /rent/{{bikeID}}
    Content-Type: application/json
    Authorization: Bearer {{jwtToken}}


### Return Bike
POST /return/{{bikeID}}
    Content-Type: application/json
    Authorization: Bearer {{jwtToken}}

{
    "rentId":"62f043861148bff3281d3738",
}
