// ctrl+alt+E to activate local env in the file
@apiPath=/stations
@host={{base_url}}{{apiPath}}

### Get Start stations 
POST / HTTP/1.1
    //Content-Type: application/json
///{longitude, latitude, radius}

### Get End stations 
POST /return HTTP/1.1
    Content-Type: application/json
    Authorization: Bearer {{jwtToken}}
///{longitude, latitude, radius}