// ctrl+alt+E to activate local env in the file
@apiPath=/users
@host={{base_url}}{{apiPath}}


### Sign Up/In with name, phone
POST /sign-in
    Content-Type: application/json

    {
        "name":"Mario2", 
        "phone": "+393456677890"
    }

### verify otp received to login
POST /verify
    Content-Type: application/json

    {
        "otp":"944699", 
        "phone": "+393456677890"
    }
### Test PayPal webhook 
POST /paypal
    Content-Type: application/json

    {"id": "new_payment"}


### Get user subscription (returns SubscriptionID or False)
GET /subscription
    Authorization: Bearer {{jwtToken}}
### Paypal create order request
POST /subscription
    Authorization: Bearer {{jwtToken}}
    Content-Type: application/json

    {"subscriptionPeriod":"Day"}
