// ctrl+alt+E to activate local env in the file
@apiPath=/users
@host={{base_url}}{{apiPath}}


### Sign Up/In by Email
POST /login/email
    Content-Type: application/json

    {
        "email":"janoradini@gmail.com", 
        "password": "secret123"
    }