// ctrl+alt+E to activate local env in the file
@apiPath=/users
@host={{base_url}}{{apiPath}}


### Sign Up/In with name, phone
POST /sign-in
    Content-Type: application/json

    {
        "name":"Mario2", 
        "phone": "+393456677890"
    }